[package]
name = "markdown_publish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.10.0"
rocket = "0.5.0"

[dev-dependencies]
reqwest = "0.12.1"
